In [1]:
import DPQNova

In [1]:
import dataframe

In [2]:
import itertools

In [ ]:
import

In [6]:
DQP = DPQNova.DinamicaPontosQuanticos(j_1_inicial=1, j_1_final=1, passoJ_1 = 0.5,
                 j_2_inicial=1, j_2_final=1, passoJ_2 = 0.5,
                 bz_1_inicial=0.1, bz_1_final=10, passoBz_1 = 0.1,
                 bz_2_inicial=0.1, bz_2_final=10, passoBz_2 = 0.1,
                 j_12_inicial=0.1, j_12_final=10, passoJ_12 = 0.1,
                 tInicial=5, tFinal=25, passoT=5)

In [2]:
DQP = DPQNova.DinamicaPontosQuanticos(j_1_inicial=1, j_1_final=1, passoJ_1 = 0.5,
                 j_2_inicial=1, j_2_final=1, passoJ_2 = 0.5,
                 bz_1_inicial=0.1, bz_1_final=10, passoBz_1 = 1.0,
                 bz_2_inicial=0.1, bz_2_final=10, passoBz_2 = 1.0,
                 j_12_inicial=0.1, j_12_final=10, passoJ_12 = 1.0,
                 tInicial=5, tFinal=25, passoT=5)

In [5]:
from multiprocessing import Pool

def f(x):
    return x*x

if __name__ == '__main__':
    with Pool(1) as p:
        print(p.map(f, [1, 2, 3]))

[1, 4, 9]

In [4]:
from numba import cuda
print(cuda.gpus)

<Managed Device 0>

In [7]:
from timeit import default_timer as timer

start = timer()
teste = DQP.criaDataFrame()
end = timer()
print(end - start)

1000000

KeyboardInterrupt:

In [5]:
teste

,j_1,j_2,bz_1,bz_2,j_12_Target,ox1T5.0,ox2T5.0,oy1T5.0,oy2T5.0,oz1T5.0,...,oy1T20.0,oy2T20.0,oz1T20.0,oz2T20.0,ox1T25.0,ox2T25.0,oy1T25.0,oy2T25.0,oz1T25.0,oz2T25.0
0,1.0,1.0,0.1,0.1,0.1,0.103177,0.103177,-0.960580,-0.960580,0.095728,...,0.222588,0.222588,0.049330,0.049330,0.214007,0.214007,-0.283409,-0.283409,0.087589,0.087589
1,1.0,1.0,0.1,0.1,1.1,0.394274,0.394274,-0.800693,-0.800693,-0.023394,...,0.072966,0.072966,-0.370300,-0.370300,0.023366,0.023366,0.662339,0.662339,-0.217931,-0.217931
2,1.0,1.0,0.1,0.1,2.1,0.580714,0.580714,-0.167632,-0.167632,0.013891,...,0.573614,0.573614,-0.122439,-0.122439,-0.117944,-0.117944,-0.123234,-0.123234,-0.182424,-0.182424
3,1.0,1.0,0.1,0.1,3.1,-0.029487,-0.029487,-0.010746,-0.010746,-0.000986,...,0.965682,0.965682,0.005876,0.005876,0.060498,0.060498,-0.240098,-0.240098,-0.046390,-0.046390
4,1.0,1.0,0.1,0.1,4.1,-0.339087,-0.339087,-0.527178,-0.527178,0.000123,...,0.830346,0.830346,0.035025,0.035025,0.136025,0.136025,-0.306828,-0.306828,-0.027868,-0.027868
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1326,1.0,1.0,10.1,10.1,6.1,0.911888,0.911888,-0.212092,-0.212092,-0.201831,...,0.124509,0.124509,-0.017185,-0.017185,0.978229,0.978229,-0.188599,-0.188599,-0.080603,-0.080603
1327,1.0,1.0,10.1,10.1,7.1,0.884365,0.884365,-0.288726,-0.288726,-0.302832,...,-0.068405,-0.068405,0.008571,0.008571,0.840581,0.840581,-0.292245,-0.292245,-0.431677,-0.431677
1328,1.0,1.0,10.1,10.1,8.1,0.752758,0.752758,-0.306285,-0.306285,-0.582006,...,-0.099616,-0.099616,-0.712712,-0.712712,0.858079,0.858079,0.321698,0.321698,-0.269658,-0.269658
1329,1.0,1.0,10.1,10.1,9.1,0.543983,0.543983,0.037956,0.037956,-0.832858,...,-0.210150,-0.210150,-0.040876,-0.040876,0.585543,0.585543,0.181860,0.181860,-0.740015,-0.740015
1330,1.0,1.0,10.1,10.1,10.1,0.739270,0.739270,0.477878,0.477878,-0.446025,...,0.059848,0.059848,0.050340,0.050340,0.650070,0.650070,0.351358,0.351358,-0.487222,-0.487222

In [4]:
from timeit import default_timer as timer
import dataframe
start = timer()
dataframe.criaFrame()
end = timer()
print(end - start)

/home/codemaster/Dinamica Pontos Quanticos/dataframe.py:206: ComplexWarning: Casting complex values to real discards the imaginary part
  ox1 = np.float32(Ox1(rovalor))
/home/codemaster/Dinamica Pontos Quanticos/dataframe.py:207: ComplexWarning: Casting complex values to real discards the imaginary part
  ox2 = np.float32(Ox2(rovalor))
/home/codemaster/Dinamica Pontos Quanticos/dataframe.py:208: ComplexWarning: Casting complex values to real discards the imaginary part
  oy1 = np.float32(Oy1(rovalor))
/home/codemaster/Dinamica Pontos Quanticos/dataframe.py:209: ComplexWarning: Casting complex values to real discards the imaginary part
  oy2 = np.float32(Oy2(rovalor))
/home/codemaster/Dinamica Pontos Quanticos/dataframe.py:210: ComplexWarning: Casting complex values to real discards the imaginary part
  oz1 = np.float32(Oz1(rovalor))
/home/codemaster/Dinamica Pontos Quanticos/dataframe.py:211: ComplexWarning: Casting complex values to real discards the imaginary part
  oz2 = np.float32(Oz2(rovalor))

colunas: 35
results shape: (286335,)
Tamanho: 286335
linhas: 8181
25.955712563009

In [2]:
print(end - start)

25.6257688489859

In [4]:
DQP.arrayT

[5.0, 10.0, 15.0, 20.0, 25.0]

TypeError: list indices must be integers or slices, not tuple

In [11]:
def soma(x,y,z):
    return x+y+z
c = map(soma, b[:])

In [12]:
list(c)

TypeError: soma() missing 2 required positional arguments: 'y' and 'z'

In [2]:
#!pip install pycaret

In [2]:
import multiprocessing as mp
print("Number of processors: ", mp.gpu_count())

AttributeError: module 'multiprocessing' has no attribute 'gpu_count'

# Valores Centrais - Variar 20%

In [2]:
mhz = 10**(-3)
pi = np.pi
j_1 = 280*mhz*2*pi
j_2 = 320*mhz*2*pi
bz_1 = (pi/16)*(10**3)*mhz
bz_2 = (pi/16)*(10**3)*mhz
j_12 = pi/140

NameError: name 'np' is not defined

In [18]:
print("j_1:{0} \nj_2:{1} \nbz_1:{2} \nbz_2:{3} \nj_12:{4}".format(j_1, j_2, bz_1, bz_2, j_12))

j_1:1.7592918860102844
j_2:2.0106192982974678
bz_1:0.19634954084936207
bz_2:0.19634954084936207
j_12:0.02243994752564138

Instacia classe com os parametros que deseja-se estudar:

In [21]:
dpq = DPQNova.DinamicaPontosQuanticos(j_1_inicial= j_1*0.8, j_1_final= j_1*1.2, passoJ_1 = 0.1,
                                      j_2_inicial= j_2*0.8, j_2_final= j_2*1.2, passoJ_2 = 0.1,
                                      bz_1_inicial= bz_1*0.8, bz_1_final= bz_1*1.2, passoBz_1 = 0.01,
                                      bz_2_inicial= bz_2*0.8, bz_2_final= bz_2*1.2, passoBz_2 = 0.01,
                                      j_12_inicial= j_12*0.8, j_12_final= j_12*1.2, passoJ_12 = 0.0001,
                                      tInicial=5, tFinal=25, passoT=5)
#dpq.saveDataFrame()

In [2]:
dpq = DPQNova.DinamicaPontosQuanticos()

Cria dataset com os parametros passados na instancia da classe:

In [3]:
df = dpq.criaDataFrame()
df.head()

colunas: 35
Total tempo gasto:  2.584614560008049
results shape: (31185,)
Tamanho: 31185
linhas: 891

,j_1,j_2,bz_1,bz_2,j_12_Target,ox1T5.0,ox2T5.0,oy1T5.0,oy2T5.0,oz1T5.0,oz2T5.0,ox1T10.0,ox2T10.0,oy1T10.0,oy2T10.0,oz1T10.0,oz2T10.0,ox1T15.0,ox2T15.0,oy1T15.0,oy2T15.0,oz1T15.0,oz2T15.0,ox1T20.0,ox2T20.0,oy1T20.0,oy2T20.0,oz1T20.0,oz2T20.0,ox1T25.0,ox2T25.0,oy1T25.0,oy2T25.0,oz1T25.0,oz2T25.0
0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0,1.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0,1.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0,1.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0,1.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
1,0.0,0.0,0.0,0.5,0.0,1.0,1.0,0.000000e+00,5.551115e-17,0.000000e+00,0.000000e+00,1.0,1.0,0.000000e+00,5.551115e-17,0.000000e+00,1.110223e-16,1.0,1.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0,1.0,0.000000e+00,1.665335e-16,0.000000e+00,1.110223e-16,1.0,1.0,0.000000e+00,6.938894e-18,0.000000e+00,0.000000e+00
2,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.000000e+00,5.551115e-17,0.000000e+00,1.110223e-16,1.0,1.0,0.000000e+00,1.665335e-16,0.000000e+00,1.110223e-16,1.0,1.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0,1.0,0.000000e+00,1.110223e-16,0.000000e+00,-2.220446e-16,1.0,1.0,0.000000e+00,1.387779e-17,0.000000e+00,0.000000e+00
3,0.0,0.0,0.5,0.0,0.0,1.0,1.0,5.551115e-17,0.000000e+00,0.000000e+00,0.000000e+00,1.0,1.0,5.551115e-17,0.000000e+00,1.110223e-16,0.000000e+00,1.0,1.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0,1.0,1.665335e-16,0.000000e+00,1.110223e-16,0.000000e+00,1.0,1.0,6.938894e-18,0.000000e+00,0.000000e+00,0.000000e+00
4,0.0,0.0,0.5,0.5,0.0,1.0,1.0,-3.191891e-16,-8.326673e-17,-5.551115e-17,-2.775558e-17,1.0,1.0,-6.938894e-17,-1.387779e-17,-1.665335e-16,2.775558e-17,1.0,1.0,8.326673e-17,8.326673e-17,1.110223e-16,1.387779e-16,1.0,1.0,-2.914335e-16,-8.326673e-17,-5.551115e-17,8.326673e-17,1.0,1.0,0.000000e+00,-1.387779e-17,-2.220446e-16,-2.775558e-17

In [21]:
df.iloc[:, 5:].head()

,ox1T5.0,ox2T5.0,oy1T5.0,oy2T5.0,oz1T5.0,oz2T5.0,ox1T10.0,ox2T10.0,oy1T10.0,oy2T10.0,...,oy1T20.0,oy2T20.0,oz1T20.0,oz2T20.0,ox1T25.0,ox2T25.0,oy1T25.0,oy2T25.0,oz1T25.0,oz2T25.0
0,1.0,1.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0,1.0,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0,1.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
1,1.0,1.0,0.000000e+00,5.551115e-17,0.000000e+00,0.000000e+00,1.0,1.0,0.000000e+00,5.551115e-17,...,0.000000e+00,1.665335e-16,0.000000e+00,1.110223e-16,1.0,1.0,0.000000e+00,6.938894e-18,0.000000e+00,0.000000e+00
2,1.0,1.0,0.000000e+00,5.551115e-17,0.000000e+00,1.110223e-16,1.0,1.0,0.000000e+00,1.665335e-16,...,0.000000e+00,1.110223e-16,0.000000e+00,-2.220446e-16,1.0,1.0,0.000000e+00,1.387779e-17,0.000000e+00,0.000000e+00
3,1.0,1.0,5.551115e-17,0.000000e+00,0.000000e+00,0.000000e+00,1.0,1.0,5.551115e-17,0.000000e+00,...,1.665335e-16,0.000000e+00,1.110223e-16,0.000000e+00,1.0,1.0,6.938894e-18,0.000000e+00,0.000000e+00,0.000000e+00
4,1.0,1.0,-3.191891e-16,-8.326673e-17,-5.551115e-17,-2.775558e-17,1.0,1.0,-6.938894e-17,-1.387779e-17,...,-2.914335e-16,-8.326673e-17,-5.551115e-17,8.326673e-17,1.0,1.0,0.000000e+00,-1.387779e-17,-2.220446e-16,-2.775558e-17

Setup dos modelos ML:

In [17]:
from sklearn.model_selection import train_test_split
from pycaret.utils import enable_colab
from pycaret.regression import * 

train, test = train_test_split(df, test_size=0.3)
regression = setup(data = df.iloc[:, 4:], target='j_12_Target', preprocess= True, use_gpu= False, normalize=True, normalize_method = 'zscore', profile=False)

In [18]:
best = compare_models(turbo = True)

## 2)Intervalos - | a = \[1;1\] ;b = \[1;1\];j= \[0;10\] ; T= \[5;25\] PJ= 0.01 | Valores maximos

Instacia classe com os parametros que deseja-se estudar:

In [7]:
dpq = DPQ.DinamicaPontosQuanticos(aInicial = 1, aFinal =1, bInicial = 1, bFinal = 1, jInicial = 0, jFinal = 10 , passoJ = 0.01)
#dpq.saveDataFrame()

Cria dataset com os parametros passados na instancia da classe:

In [8]:
df = dpq.criaDataFrame()
df

colunas: 33
Total tempo gasto:  2.5631345299771056
results shape: (33033,)
Tamanho: 33033
linhas: 1001

,a,b,jTarget,ox1T5.0,ox2T5.0,oy1T5.0,oy2T5.0,oz1T5.0,oz2T5.0,ox1T10.0,...,oy1T20.0,oy2T20.0,oz1T20.0,oz2T20.0,ox1T25.0,ox2T25.0,oy1T25.0,oy2T25.0,oz1T25.0,oz2T25.0
0,1.0,1.0,0.00,0.497516,0.497516,0.707098,0.707098,0.502484,0.502484,0.000025,...,0.014053,0.014053,0.000099,0.000099,0.487580,0.487580,0.706889,0.706889,0.512420,0.512420
1,1.0,1.0,0.01,0.487879,0.487879,0.707669,0.707669,0.510751,0.510751,-0.004102,...,0.064429,0.064429,0.003319,0.003319,0.442105,0.442105,0.700658,0.700658,0.556123,0.556123
2,1.0,1.0,0.02,0.477927,0.477927,0.707715,0.707715,0.519119,0.519119,-0.006807,...,0.115242,0.115242,0.011603,0.011603,0.395928,0.395928,0.683165,0.683165,0.599621,0.599621
3,1.0,1.0,0.03,0.467669,0.467669,0.707228,0.707228,0.527577,0.527577,-0.008055,...,0.165912,0.165912,0.024948,0.024948,0.349867,0.349867,0.654482,0.654482,0.642139,0.642139
4,1.0,1.0,0.04,0.457114,0.457114,0.706202,0.706202,0.536118,0.536118,-0.007814,...,0.215823,0.215823,0.043292,0.043292,0.304795,0.304795,0.614879,0.614879,0.682875,0.682875
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,1.0,1.0,9.96,-0.672354,-0.672354,-0.362066,-0.362066,-0.029392,-0.029392,0.100142,...,-0.593779,-0.593779,0.096086,0.096086,-0.811594,-0.811594,0.361548,0.361548,-0.019323,-0.019323
997,1.0,1.0,9.97,-0.623281,-0.623281,-0.332874,-0.332874,-0.032814,-0.032814,0.012776,...,-0.786837,-0.786837,0.071875,0.071875,-0.829448,-0.829448,0.369549,0.369549,0.001317,0.001317
998,1.0,1.0,9.98,-0.568084,-0.568084,-0.299936,-0.299936,-0.035863,-0.035863,-0.077098,...,-0.867705,-0.867705,0.041535,0.041535,-0.646117,-0.646117,0.278615,0.278615,0.021809,0.021809
999,1.0,1.0,9.99,-0.507298,-0.507298,-0.263570,-0.263570,-0.038510,-0.038510,-0.166004,...,-0.824008,-0.824008,0.009715,0.009715,-0.305074,-0.305074,0.110495,0.110495,0.037289,0.037289
1000,1.0,1.0,10.00,-0.441510,-0.441510,-0.224128,-0.224128,-0.040730,-0.040730,-0.250505,...,-0.662457,-0.662457,-0.018717,-0.018717,0.112677,0.112677,-0.094756,-0.094756,0.044098,0.044098

Setup dos modelos ML:

In [5]:
from sklearn.model_selection import train_test_split
from pycaret.utils import enable_colab
from pycaret.regression import * 

train, test = train_test_split(df, test_size=0.3)
regression = setup(data = df, target='jTarget', preprocess= True, use_gpu= False, normalize=True, normalize_method = 'zscore', profile=False)

In [6]:
best = compare_models(turbo = True)

## 3)Intervalos - | a = \[1;1\] ;b = \[1;1\];j= \[0;10\] ; T= \[5;25\] PJ= 0.001 | Valores minimos

Instacia classe com os parametros que deseja-se estudar:

In [10]:
dpq = DPQ.DinamicaPontosQuanticos(aInicial = 1, aFinal =1, bInicial = 1, bFinal = 1, jInicial = 0, jFinal = 10 , passoJ = 0.001)
#dpq.saveDataFrame()

Cria dataset com os parametros passados na instancia da classe:

In [11]:
df = dpq.criaDataFrame()
df

colunas: 33
Total tempo gasto:  51.94533231901005
results shape: (330033,)
Tamanho: 330033
linhas: 10001

,a,b,jTarget,ox1T5.0,ox2T5.0,oy1T5.0,oy2T5.0,oz1T5.0,oz2T5.0,ox1T10.0,...,oy1T20.0,oy2T20.0,oz1T20.0,oz2T20.0,ox1T25.0,ox2T25.0,oy1T25.0,oy2T25.0,oz1T25.0,oz2T25.0
0,1.0,1.0,0.000,0.497516,0.497516,0.707098,0.707098,0.502484,0.502484,0.000025,...,0.014053,0.014053,0.000099,0.000099,0.487580,0.487580,0.706889,0.706889,0.512420,0.512420
1,1.0,1.0,0.001,0.496566,0.496566,0.707179,0.707179,0.503306,0.503306,-0.000451,...,0.019055,0.019055,0.000194,0.000194,0.483086,0.483086,0.706770,0.706770,0.516779,0.516779
2,1.0,1.0,0.002,0.495614,0.495614,0.707254,0.707254,0.504129,0.504129,-0.000912,...,0.024066,0.024066,0.000340,0.000340,0.478578,0.478578,0.706540,0.706540,0.521141,0.521141
3,1.0,1.0,0.003,0.494658,0.494658,0.707324,0.707324,0.504953,0.504953,-0.001360,...,0.029086,0.029086,0.000535,0.000535,0.474057,0.474057,0.706198,0.706198,0.525508,0.525508
4,1.0,1.0,0.004,0.493699,0.493699,0.707389,0.707389,0.505778,0.505778,-0.001794,...,0.034115,0.034115,0.000781,0.000781,0.469523,0.469523,0.705744,0.705744,0.529878,0.529878
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9996,1.0,1.0,9.996,-0.468385,-0.468385,-0.240250,-0.240250,-0.039895,-0.039895,-0.217447,...,-0.740007,-0.740007,-0.008049,-0.008049,-0.057415,-0.057415,-0.011260,-0.011260,0.042570,0.042570
9997,1.0,1.0,9.997,-0.461734,-0.461734,-0.236261,-0.236261,-0.040110,-0.040110,-0.225816,...,-0.722143,-0.722143,-0.010819,-0.010819,-0.014907,-0.014907,-0.032136,-0.032136,0.043106,0.043106
9998,1.0,1.0,9.998,-0.455037,-0.455037,-0.232244,-0.232244,-0.040321,-0.040321,-0.234117,...,-0.703243,-0.703243,-0.013523,-0.013523,0.027680,0.027680,-0.053044,-0.053044,0.043540,0.043540
9999,1.0,1.0,9.999,-0.448296,-0.448296,-0.228200,-0.228200,-0.040528,-0.040528,-0.242348,...,-0.683338,-0.683338,-0.016157,-0.016157,0.070242,0.070242,-0.073934,-0.073934,0.043871,0.043871
10000,1.0,1.0,10.000,-0.441510,-0.441510,-0.224128,-0.224128,-0.040730,-0.040730,-0.250505,...,-0.662457,-0.662457,-0.018717,-0.018717,0.112677,0.112677,-0.094756,-0.094756,0.044098,0.044098

Setup dos modelos ML:

In [12]:
from sklearn.model_selection import train_test_split
from pycaret.utils import enable_colab
from pycaret.regression import * 

train, test = train_test_split(df, test_size=0.3)
regression = setup(data = df, target='jTarget', preprocess= True, use_gpu= False, normalize=True, normalize_method = 'zscore', profile=False)

In [13]:
best = compare_models(turbo = True)

## 4)Intervalos - | a = \[0;1\] ;b = \[0;1\];j= \[0;10\] ; T= \[5;25\] PJ= 0.1 | Valores minimos

Instacia classe com os parametros que deseja-se estudar:

In [15]:
dpq = DPQ.DinamicaPontosQuanticos(aInicial = 0, aFinal =1, bInicial = 0, bFinal = 1, jInicial = 0, jFinal = 10 , passoJ = 0.1)
#dpq.saveDataFrame()

Cria dataset com os parametros passados na instancia da classe:

In [16]:
df = dpq.criaDataFrame()
df

colunas: 33
Total tempo gasto:  65.94974379701307
results shape: (403293,)
Tamanho: 403293
linhas: 12221

,a,b,jTarget,ox1T5.0,ox2T5.0,oy1T5.0,oy2T5.0,oz1T5.0,oz2T5.0,ox1T10.0,...,oy1T20.0,oy2T20.0,oz1T20.0,oz2T20.0,ox1T25.0,ox2T25.0,oy1T25.0,oy2T25.0,oz1T25.0,oz2T25.0
0,0.0,0.0,0.0,-0.839072,-0.839072,-0.544021,-0.544021,0.000000,0.000000e+00,0.408082,...,0.745113,0.745113,0.000000,0.000000e+00,0.964966,0.964966,-0.262375,-0.262375,0.000000,0.000000e+00
1,0.0,0.1,0.0,-0.792976,-0.839072,-0.582272,-0.544021,0.179298,1.387779e-16,0.321918,...,0.595191,0.745113,0.178354,3.608225e-16,0.999872,0.964966,-0.016024,-0.262375,0.000013,3.330669e-16
2,0.0,0.2,0.0,-0.649651,-0.839072,-0.684909,-0.544021,0.329930,-3.330669e-16,0.061800,...,0.047587,0.745113,0.384389,-1.332268e-15,0.758356,0.964966,0.650047,-0.262375,0.048329,-9.992007e-16
3,0.0,0.3,0.0,-0.401074,-0.839072,-0.813922,-0.544021,0.420322,-2.220446e-16,-0.324937,...,-0.762351,0.745113,0.441855,-8.604228e-16,-0.245125,0.964966,0.894642,-0.262375,0.373538,1.054712e-15
4,0.0,0.4,0.0,-0.054608,-0.839072,-0.905023,-0.544021,0.421843,1.942890e-16,-0.638133,...,-0.727865,0.745113,0.130744,7.494005e-16,-0.640340,0.964966,-0.399312,-0.262375,0.656136,-6.661338e-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12216,1.0,0.6,10.0,-0.741288,-0.744808,-0.418841,-0.412157,-0.019645,-2.663367e-02,0.169680,...,-0.267864,-0.195231,0.021237,1.368194e-01,-0.539729,-0.564947,0.239840,0.185378,-0.068641,3.416633e-03
12217,1.0,0.7,10.0,-0.689400,-0.692419,-0.384204,-0.378373,-0.024896,-2.991090e-02,0.086353,...,-0.583573,-0.539176,0.032817,1.167478e-01,-0.824852,-0.834204,0.352582,0.332891,-0.045108,4.223671e-03
12218,1.0,0.8,10.0,-0.622942,-0.625106,-0.340502,-0.336220,-0.030381,-3.346449e-02,-0.015204,...,-0.810209,-0.789119,0.030586,7.846539e-02,-0.827417,-0.826359,0.348557,0.350905,-0.012560,1.626291e-02
12219,1.0,0.9,10.0,-0.540570,-0.541664,-0.287186,-0.284945,-0.035795,-3.713569e-02,-0.130300,...,-0.856733,-0.850732,0.011551,2.892207e-02,-0.482378,-0.478631,0.189184,0.196791,0.021579,3.362593e-02
12220,1.0,1.0,10.0,-0.441510,-0.441510,-0.224128,-0.224128,-0.040730,-4.073001e-02,-0.250505,...,-0.662457,-0.662457,-0.018717,-1.871686e-02,0.112677,0.112677,-0.094756,-0.094756,0.044098,4.409769e-02

Setup dos modelos ML:

In [17]:
from sklearn.model_selection import train_test_split
from pycaret.utils import enable_colab
from pycaret.regression import * 

train, test = train_test_split(df, test_size=0.3)
regression = setup(data = df, target='jTarget', preprocess= True, use_gpu= False, normalize=True, normalize_method = 'zscore', profile=False)

In [18]:
best = compare_models(turbo = True)

## 5)Intervalos - | a = \[0;1\] ;b = \[0;1\];j= \[0;10\] ; T= \[5;25\] PJ= 0.01 | Valores minimos

Instacia classe com os parametros que deseja-se estudar:

In [19]:
dpq = DPQ.DinamicaPontosQuanticos(aInicial = 0, aFinal =1, bInicial = 0, bFinal = 1, jInicial = 0, jFinal = 10 , passoJ = 0.01)
#dpq.saveDataFrame()

Cria dataset com os parametros passados na instancia da classe:

In [20]:
df = dpq.criaDataFrame()
df

colunas: 33
Total tempo gasto:  948.8581488599884
results shape: (3996993,)
Tamanho: 3996993
linhas: 121121

,a,b,jTarget,ox1T5.0,ox2T5.0,oy1T5.0,oy2T5.0,oz1T5.0,oz2T5.0,ox1T10.0,...,oy1T20.0,oy2T20.0,oz1T20.0,oz2T20.0,ox1T25.0,ox2T25.0,oy1T25.0,oy2T25.0,oz1T25.0,oz2T25.0
0,0.0,0.0,0.0,-0.839072,-0.839072,-0.544021,-0.544021,0.000000,0.000000e+00,0.408082,...,0.745113,0.745113,0.000000,0.000000e+00,0.964966,0.964966,-0.262375,-0.262375,0.000000,0.000000e+00
1,0.0,0.1,0.0,-0.792976,-0.839072,-0.582272,-0.544021,0.179298,1.387779e-16,0.321918,...,0.595191,0.745113,0.178354,3.608225e-16,0.999872,0.964966,-0.016024,-0.262375,0.000013,3.330669e-16
2,0.0,0.2,0.0,-0.649651,-0.839072,-0.684909,-0.544021,0.329930,-3.330669e-16,0.061800,...,0.047587,0.745113,0.384389,-1.332268e-15,0.758356,0.964966,0.650047,-0.262375,0.048329,-9.992007e-16
3,0.0,0.3,0.0,-0.401074,-0.839072,-0.813922,-0.544021,0.420322,-2.220446e-16,-0.324937,...,-0.762351,0.745113,0.441855,-8.604228e-16,-0.245125,0.964966,0.894642,-0.262375,0.373538,1.054712e-15
4,0.0,0.4,0.0,-0.054608,-0.839072,-0.905023,-0.544021,0.421843,1.942890e-16,-0.638133,...,-0.727865,0.745113,0.130744,7.494005e-16,-0.640340,0.964966,-0.399312,-0.262375,0.656136,-6.661338e-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121116,1.0,0.6,10.0,-0.741288,-0.744808,-0.418841,-0.412157,-0.019645,-2.663367e-02,0.169680,...,-0.267864,-0.195231,0.021237,1.368194e-01,-0.539729,-0.564947,0.239840,0.185378,-0.068641,3.416633e-03
121117,1.0,0.7,10.0,-0.689400,-0.692419,-0.384204,-0.378373,-0.024896,-2.991090e-02,0.086353,...,-0.583573,-0.539176,0.032817,1.167478e-01,-0.824852,-0.834204,0.352582,0.332891,-0.045108,4.223671e-03
121118,1.0,0.8,10.0,-0.622942,-0.625106,-0.340502,-0.336220,-0.030381,-3.346449e-02,-0.015204,...,-0.810209,-0.789119,0.030586,7.846539e-02,-0.827417,-0.826359,0.348557,0.350905,-0.012560,1.626291e-02
121119,1.0,0.9,10.0,-0.540570,-0.541664,-0.287186,-0.284945,-0.035795,-3.713569e-02,-0.130300,...,-0.856733,-0.850732,0.011551,2.892207e-02,-0.482378,-0.478631,0.189184,0.196791,0.021579,3.362593e-02
121120,1.0,1.0,10.0,-0.441510,-0.441510,-0.224128,-0.224128,-0.040730,-4.073001e-02,-0.250505,...,-0.662457,-0.662457,-0.018717,-1.871686e-02,0.112677,0.112677,-0.094756,-0.094756,0.044098,4.409769e-02

Setup dos modelos ML:

In [21]:
from sklearn.model_selection import train_test_split
from pycaret.utils import enable_colab
from pycaret.regression import * 

train, test = train_test_split(df, test_size=0.3)
regression = setup(data = df, target='jTarget', preprocess= True, use_gpu= False, normalize=True, normalize_method = 'zscore', profile=False)

In [ ]:
best = compare_models(turbo = True)

IntProgress(value=0, description='Processing: ', max=99)

Initiated  . . . . . . . . . . . . . . . . . .            09:48:22
Status     . . . . . . . . . . . . . . . . . .    Fitting 10 Folds
Estimator  . . . . . . . . . . . . . . . . . .  AdaBoost Regressor

## 6)Intervalos - | a = \[0;1\] ;b = \[0;1\];j= \[0;10\] ; T= \[5;25\] PJ= 0.001 | Valores minimos

Instacia classe com os parametros que deseja-se estudar:

In [ ]:
dpq = DPQ.DinamicaPontosQuanticos(aInicial = 0, aFinal =1, bInicial = 0, bFinal = 1, jInicial = 0, jFinal = 10 , passoJ = 0.001)
dpq.saveDataFrame()

Cria dataset com os parametros passados na instancia da classe:

In [ ]:
df = dpq.criaDataFrame()
#df

Setup dos modelos ML:

In [ ]:
from sklearn.model_selection import train_test_split
from pycaret.utils import enable_colab
from pycaret.regression import * 

train, test = train_test_split(df, test_size=0.3)
regression = setup(data = df, target='jTarget', preprocess= True, use_gpu= False, normalize=True, normalize_method = 'zscore', profile=False)

In [ ]:
best = compare_models(turbo = True)

5)Intervalos - | a = \[0;1\] ;b = \[0;1\];j= \[1;10\] ; T= \[5;25\] PJ= 0.001 | Fazer
-Incluir a e b na tabela
a b variando de [0: 5] com passo de 0.1, J = 0.01 variando de [1:10] e salvar.

Adicionar um erro Y randomico nas features da base de test e observar os resultados
ir aumentando o valor de Y.
Treinar com os dados da equação.

In [27]:
for j in range(10):
    dpq = DPQ.DinamicaPontosQuanticos(aInicial = 0, aFinal =1, bInicial = 0, bFinal = 1, jInicial = (0+j), jFinal = (1+j) , passoJ = 0.001)
    dpq.saveDataFrame()

colunas: 31
Total tempo gasto:  630.5462845399743
results shape: (3754751,)
Tamanho: 3754751
linhas: 121121
colunas: 31
Total tempo gasto:  472.494080539007
results shape: (3754751,)
Tamanho: 3754751
linhas: 121121
colunas: 31
Total tempo gasto:  472.18935264699394
results shape: (3754751,)
Tamanho: 3754751
linhas: 121121
colunas: 31
Total tempo gasto:  456.9324120240053
results shape: (3754751,)
Tamanho: 3754751
linhas: 121121
colunas: 31
Total tempo gasto:  460.18995909098885
results shape: (3754751,)
Tamanho: 3754751
linhas: 121121
colunas: 31
Total tempo gasto:  457.4107160830172
results shape: (3754751,)
Tamanho: 3754751
linhas: 121121
colunas: 31
Total tempo gasto:  456.71186900301836
results shape: (3754751,)
Tamanho: 3754751
linhas: 121121
colunas: 31
Total tempo gasto:  456.52695341198705
results shape: (3754751,)
Tamanho: 3754751
linhas: 121121
colunas: 31
Total tempo gasto:  458.9572986989515
results shape: (3754751,)
Tamanho: 3754751
linhas: 121121
colunas: 31
Total tempo gasto:  458.37021893501515
results shape: (3754751,)
Tamanho: 3754751
linhas: 121121

In [2]:
import pandas as pd

In [3]:
df_1 = pd.read_csv("data/Tabelas/[0:1][0:1][0:1][5:25].csv")
df_2 = pd.read_csv("data/Tabelas/[0:1][0:1][1:2][5:25].csv")
df_3 = pd.read_csv("data/Tabelas/[0:1][0:1][2:3][5:25].csv")
df_4 = pd.read_csv("data/Tabelas/[0:1][0:1][3:4][5:25].csv")
df_5 = pd.read_csv("data/Tabelas/[0:1][0:1][4:5][5:25].csv")
df_6 = pd.read_csv("data/Tabelas/[0:1][0:1][5:6][5:25].csv")
df_7 = pd.read_csv("data/Tabelas/[0:1][0:1][6:7][5:25].csv")
df_8 = pd.read_csv("data/Tabelas/[0:1][0:1][7:8][5:25].csv")
df_9 = pd.read_csv("data/Tabelas/[0:1][0:1][8:9][5:25].csv")
df_10 = pd.read_csv("data/Tabelas/[0:1][0:1][9:10][5:25].csv")

In [4]:
df_total = pd.concat([df_1, df_2, df_3, df_4, df_5, df_6, df_7, df_8, df_9, df_10])

In [8]:
print("O data set tem um total de {} linhas".format(len(df_total)))

O data set tem um total de 1210121 linhas

In [6]:
df_total = df_total.drop('Unnamed: 0',axis=1)

In [7]:
df_total = df_total.drop_duplicates()

In [9]:
print("O removenddo linhas duplicadas tem um total de {} linhas".format(len(df_total)))

O removenddo linhas duplicadas tem um total de 1210121 linhas

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import ExtraTreeRegressor
from sklearn.metrics import max_error, mean_absolute_error, mean_squared_error,r2_score


X = df_total.iloc[:,3:]
y = df_total.iloc[:, :3]
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=7, test_size=0.3)
extra_tree = ExtraTreeRegressor(random_state=0)
et_reg = BaggingRegressor(extra_tree, random_state=0).fit(X_train, y_train["jTarget"])

y_pred = et_reg.predict(X_test)
maximo = max_error(y_test["jTarget"], y_pred)
mea = mean_absolute_error(y_test["jTarget"], y_pred)
meq = mean_squared_error(y_test["jTarget"], y_pred)
r2 = r2_score(y_test["jTarget"], y_pred)
print("máximo erro residual:", maximo)
print("Média do erro absoluto:", mea)
print("Média do erro ao quadrado:", meq)
print("r2:", r2)

máximo erro residual: 8.782499999999999
Média do erro absoluto: 0.47408952082438516
Média do erro ao quadrado: 0.8897848109792176
r2: 0.8931556669449188

In [113]:
from sklearn.svm import SVR

svr_reg = SVR().fit(X_train,y_train["jTarget"])
y_pred = svr_reg.predict(X_test)

maximo = max_error(y_test["jTarget"], y_pred)
mea = mean_absolute_error(y_test["jTarget"], y_pred)
meq = mean_squared_error(y_test["jTarget"], y_pred)
r2 = r2_score(y_test["jTarget"], y_pred)
print("máximo erro residual:", maximo)
print("Média do erro absoluto:", mea)
print("Média do erro ao quadrado:", meq)
print("r2:", r2)

máximo erro residual: 0.5487810812103895
Média do erro absoluto: 0.2447081357228149
Média do erro ao quadrado: 0.08754149311026123
r2: -0.05735527372362892

In [114]:
from catboost import CatBoostRegressor

cat_reg = CatBoostRegressor(verbose=0, n_estimators=100)
cat_reg = cat_reg.fit(X_train, y_train["jTarget"])
y_pred = cat_reg.predict(X_test)

maximo = max_error(y_test["jTarget"], y_pred)
mea = mean_absolute_error(y_test["jTarget"], y_pred)
meq = mean_squared_error(y_test["jTarget"], y_pred)
r2 = r2_score(y_test["jTarget"], y_pred)
print("máximo erro residual:", maximo)
print("Média do erro absoluto:", mea)
print("Média do erro ao quadrado:", meq)
print("r2:", r2)

máximo erro residual: 0.654822756726249
Média do erro absoluto: 0.15957598799165312
Média do erro ao quadrado: 0.04117215561081934
r2: 0.5027090089628947

In [ ]:
from sklearn.ensemble import RandomForestRegressor

rfr_reg = RandomForestRegressor(random_state=0)
rfr_reg = rfr_reg.fit(X_train, y_train["jTarget"])
y_pred = rfr_reg.predict(X_test)

maximo = max_error(y_test["jTarget"], y_pred)
mea = mean_absolute_error(y_test["jTarget"], y_pred)
meq = mean_squared_error(y_test["jTarget"], y_pred)
r2 = r2_score(y_test["jTarget"], y_pred)
print("máximo erro residual:", maximo)
print("Média do erro absoluto:", mea)
print("Média do erro ao quadrado:", meq)
print("r2:", r2)

In [120]:
models = [("random forest regressor",rfr_reg), ("cat boosting", cat_reg), ("svr" , svr_reg), ("Extra tree" , et_reg)]

In [124]:
models[1][0]

'cat boosting'

In [148]:
print("Resultados")
print("{:25}||{:12}||{:12}||{:12}||{}".format("Método", "max.err.res.", "Med.err.abs.", "Med.err.quad.", "r2"))
print(90*"=")
for model in models:
    y_pred = model[1].predict(X_test)
    
    maximo = max_error(y_test["jTarget"], y_pred)
    mea = mean_absolute_error(y_test["jTarget"], y_pred)
    meq = mean_squared_error(y_test["jTarget"], y_pred)
    r2 = r2_score(y_test["jTarget"], y_pred)
    print("{:25}||{:12.3f}||{:12.3f}||{:13.3f}||{:2.3f}".format(model[0], maximo, mea, meq, r2))
    print(90*"-")

Resultados
Método                   ||max.err.res.||Med.err.abs.||Med.err.quad.||r2
==========================================================================================
random forest regressor  ||       0.605||       0.061||        0.015||0.823
------------------------------------------------------------------------------------------
cat boosting             ||       0.655||       0.160||        0.041||0.503
------------------------------------------------------------------------------------------
svr                      ||       0.549||       0.245||        0.088||-0.057
------------------------------------------------------------------------------------------
Extra tree               ||       0.652||       0.065||        0.018||0.783
------------------------------------------------------------------------------------------

Com essa base o Método random forest regressor obteve o melhor desempenho e será o utilizado apartir deste ponto.

Vamos analisar como o random forest regressor está performando conforme os valores de j,a e b.
Para isso agora será plotado o grafico do erro x intervalo (j,a,b)

In [ ]:
#Captura as predições para a base de teste
y_pred = rfr_reg.predict(X_test)

#Captura o erro para cada predição
erro = np.array([])
for y, pred in zip(y_test['jTarget'], y_pred):
    erro = np.append(erro, abs(y_pred - y_test['jTarget']))